import { describe, expect, it } from "vitest";
import { cleanTranscript, cleanTranscriptLine, composeSourceTopic, countWords, detectTextLanguage, parseSubtitleDocument, textOverlapRatio, truncateAtBoundary } from "./transcript.js";
import { classifyIntakeUrl, parseTikTokUrl } from "./url-intake.js";

const VTT = `WEBVTT
Kind: captions
Language: ja

NOTE generated by TikTok

1
00:00:00.000 --> 00:00:01.500
<c.colorE5E5E5>今日は</c>大阪の

2
00:00:01.500 --> 00:00:03.000
今日は大阪の新しい駅を紹介します

00:00:03.000 --> 00:00:04.200 align:start position:0%
[音楽]

00:00:04.200 --> 00:00:06.000
2025年に開業予定です&amp;楽しみ♪

00:00:06.000 --> 00:00:07.000
2025年に開業予定です&amp;楽しみ♪
`;

const SRT = `1
00:00:00,000 --> 00:00:02,000
Tokyo Tower turns 67 this year.

2
00:00:02,000 --> 00:00:04,500
It is 333 meters tall. 🗼

3
00:00:04,500 --> 00:00:06,000
It is 333 meters tall.
`;

describe("VE2E-96 subtitles -> clean transcript", () => {
  it("parses WebVTT: header / NOTE / cue ids / timings / markup removed, entities decoded", () => {
    expect(parseSubtitleDocument(VTT)).toEqual(["今日は大阪の", "今日は大阪の新しい駅を紹介します", "[音楽]", "2025年に開業予定です&楽しみ♪", "2025年に開業予定です&楽しみ♪"]);
  });

  it("cleans: rolling and repeated captions merged, sound tags / notes / emoji / timestamps dropped, facts kept", () => {
    expect(cleanTranscript(parseSubtitleDocument(VTT))).toBe("今日は大阪の新しい駅を紹介します2025年に開業予定です&楽しみ");
    expect(cleanTranscript(parseSubtitleDocument(SRT))).toBe("Tokyo Tower turns 67 this year. It is 333 meters tall.");
    expect(cleanTranscriptLine("[00:12] (Music) hello   world >> again!!!! ​")).toBe("hello world again!");
  });

  it("drops a long sentence said again later, keeps short repeats", () => {
    expect(cleanTranscript("The new station opens in March next year. Yes. Then more news. Yes. The new station opens in March next year.")).toBe("The new station opens in March next year. Yes. Then more news. Yes.");
  });

  it("plain text (STT output) is cleaned the same way", () => {
    expect(cleanTranscript("  hello   there  \n\n hello there \n how are you ")).toBe("hello there how are you");
  });
});

describe("VE2E-96 language, length, overlap", () => {
  it("guesses the language from the script", () => {
    expect(detectTextLanguage("今日は大阪の新しい駅を紹介します")).toBe("ja");
    expect(detectTextLanguage("오늘은 서울의 새 역을 소개합니다")).toBe("ko");
    expect(detectTextLanguage("今天介绍大阪的新车站")).toBe("zh");
    expect(detectTextLanguage("Hôm nay chúng tôi giới thiệu nhà ga mới ở Osaka")).toBe("vi");
    expect(detectTextLanguage("Today we visit the new station in Osaka")).toBe("en");
    expect(detectTextLanguage("12345 !!!")).toBeNull();
  });

  it("counts words, Japanese included", () => {
    expect(countWords("Tokyo Tower is 333 meters tall.")).toBe(6);
    expect(countWords("東京タワーは高い")).toBeGreaterThan(1);
  });

  it("overlap: a copy is 1, a real rewrite is low", () => {
    const source = "The city council approved a new budget of 12 million dollars on Monday to repair old bridges across the river.";
    expect(textOverlapRatio(source, source)).toBe(1);
    expect(textOverlapRatio(source, "Old bridges will finally get fixed: on Monday, councillors signed off 12 million dollars for the work.")).toBeLessThan(0.2);
    const ja = "大阪市は月曜日、川に架かる古い橋の修理に1200万ドルの新予算を承認しました。";
    expect(textOverlapRatio(ja, ja)).toBe(1);
    expect(textOverlapRatio(ja, "古い橋がついに直ります。月曜日、市議会が修理費として1200万ドルを決めました。")).toBeLessThan(0.2);
  });
});

describe("VE2E-96 topic from analysed text", () => {
  it("cuts at a sentence end, else a clause mark, else a space - never inside a word", () => {
    expect(truncateAtBoundary("First sentence here. Second sentence that is long.", 30)).toBe("First sentence here.…");
    expect(truncateAtBoundary("one two three four five six seven eight", 20)).toBe("one two three four…");
    expect(truncateAtBoundary("新しい駅が開業します。来年三月の予定です。", 15)).toBe("新しい駅が開業します。…");
    expect(truncateAtBoundary("short", 20)).toBe("short");
  });

  it("fits the 400-character topic limit and always names the source", () => {
    const topic = composeSourceTopic({ text: "A sentence about the news. ".repeat(40), sourceName: "Example News", sourceUrl: "https://example.com/a" });
    expect([...topic].length).toBeLessThanOrEqual(400);
    expect(topic.endsWith("Source: Example News - https://example.com/a")).toBe(true);
    const longUrl = composeSourceTopic({ text: "短い本文。", sourceName: null, sourceUrl: `https://example.com/${"a".repeat(300)}` });
    expect(longUrl).toBe("短い本文。\n\nSource: example.com");
  });
});

describe("VE2E-96 TikTok URLs", () => {
  it("accepts video links (canonical / mobile) and short links (vm, vt, /t/)", () => {
    expect(parseTikTokUrl("https://www.tiktok.com/@osaka.news/video/7412345678901234567?is_from_webapp=1")).toEqual({ kind: "video", videoId: "7412345678901234567", url: "https://www.tiktok.com/@osaka.news/video/7412345678901234567" });
    expect(parseTikTokUrl("tiktok.com/@a_b/video/7412345678901234567/")).toMatchObject({ kind: "video", videoId: "7412345678901234567" });
    expect(parseTikTokUrl("https://m.tiktok.com/v/7412345678901234567.html")).toMatchObject({ kind: "video", videoId: "7412345678901234567" });
    expect(parseTikTokUrl("https://vm.tiktok.com/ZMabc123/")).toEqual({ kind: "short", url: "https://vm.tiktok.com/ZMabc123/" });
    expect(parseTikTokUrl("vt.tiktok.com/ZSxyz789")).toEqual({ kind: "short", url: "https://vt.tiktok.com/ZSxyz789/" });
    expect(parseTikTokUrl("https://www.tiktok.com/t/ZTabcde12/")).toEqual({ kind: "short", url: "https://www.tiktok.com/t/ZTabcde12/" });
  });

  it("rejects what is not a TikTok video: profile, photo post, other subdomain, look-alike host", () => {
    for (const raw of ["https://www.tiktok.com/@osaka.news", "https://www.tiktok.com/@a/photo/7412345678901234567", "https://shop.tiktok.com/view/product/1", "https://www.tiktok.com/@a/video/abc", "https://faketiktok.com/@a/video/7412345678901234567", "https://vm.tiktok.com/"]) {
      expect(parseTikTokUrl(raw), raw).toBeNull();
    }
    expect(classifyIntakeUrl("https://shop.tiktok.com/view/product/1")).toMatchObject({ ok: true, kind: "tiktok" }); // never read as an article
  });
});
